# Site settings
title: Moving To The Dark Side
subtitle: Leaving the Pipette for a Keyboard
email: amjdomingues@gmail.com
description: ""
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://adomingues.github.io/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  adomingues

author:
  login: fridaymeetssunday
  email: amjdomingues@gmail.com
  display_name: fridaymeetssunday
  first_name: 'Antonio'
  last_name: 'Domingues'

# Build settings
markdown: redcarpet
highlighter: pygments


# Your disqus shortname, entering this will enable commenting on posts
disqus: fridaymeetssunday
